IF EXISTS (SELECT 1
          FROM SYSOBJECTS
          WHERE ID = OBJECT_ID('TRG_UPDATE_INSERT_AA10')
          AND TYPE = 'TR')
   DROP TRIGGER TRG_UPDATE_INSERT_AA10
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TAORGMG') AND O.NAME = 'FK_TAORGMG_REFERENCE_TAORG')
ALTER TABLE TAORGMG
   DROP CONSTRAINT FK_TAORGMG_REFERENCE_TAORG
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TAORGMG') AND O.NAME = 'FK_TAORGMG_REFERENCE_TAPOSITI')
ALTER TABLE TAORGMG
   DROP CONSTRAINT FK_TAORGMG_REFERENCE_TAPOSITI
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TASHAREPOSITION') AND O.NAME = 'FK_TASHAREP_REFERENCE_TAPOSITI')
ALTER TABLE TASHAREPOSITION
   DROP CONSTRAINT FK_TASHAREP_REFERENCE_TAPOSITI
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TASHAREPOSITION') AND O.NAME = 'FK_TASHAREP_REFERENCE_TAPOSITI')
ALTER TABLE TASHAREPOSITION
   DROP CONSTRAINT FK_TASHAREP_REFERENCE_TAPOSITI
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TACOMMONMENU') AND O.NAME = 'FK_TACOMMON_REFERENCE_TAUSER')
ALTER TABLE TACOMMONMENU
   DROP CONSTRAINT FK_TACOMMON_REFERENCE_TAUSER
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TACOMMONMENU') AND O.NAME = 'FK_TACOMMON_REFERENCE_TAMENU')
ALTER TABLE TACOMMONMENU
   DROP CONSTRAINT FK_TACOMMON_REFERENCE_TAMENU
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TAORG') AND O.NAME = 'FK_TAORG_REFERENCE_TAORG')
ALTER TABLE TAORG
   DROP CONSTRAINT FK_TAORG_REFERENCE_TAORG
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TAPOSITION') AND O.NAME = 'FK_TAPOSITI_RELATIONS_TAORG')
ALTER TABLE TAPOSITION
   DROP CONSTRAINT FK_TAPOSITI_RELATIONS_TAORG
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TAPOSITIONAUTHRITY') AND O.NAME = 'FK_TAPOSITI_REFERENCE_TAMENU')
ALTER TABLE TAPOSITIONAUTHRITY
   DROP CONSTRAINT FK_TAPOSITI_REFERENCE_TAMENU
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TAPOSITIONAUTHRITY') AND O.NAME = 'FK_TAPOSITI_RELATIONS_TAPOSITI')
ALTER TABLE TAPOSITIONAUTHRITY
   DROP CONSTRAINT FK_TAPOSITI_RELATIONS_TAPOSITI
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TAUSERPOSITION') AND O.NAME = 'FK_TAUSERPO_RELATIONS_TAPOSITI')
ALTER TABLE TAUSERPOSITION
   DROP CONSTRAINT FK_TAUSERPO_RELATIONS_TAPOSITI
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TAUSERPOSITION') AND O.NAME = 'FK_TAUSERPO_RELATIONS_TAUSER')
ALTER TABLE TAUSERPOSITION
   DROP CONSTRAINT FK_TAUSERPO_RELATIONS_TAUSER
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TAMANAGERMG') AND O.NAME = 'FK_TAMANAGE_REFERENCE_TAORG')
ALTER TABLE TAMANAGERMG
   DROP CONSTRAINT FK_TAMANAGE_REFERENCE_TAORG
go

IF EXISTS (SELECT 1
   FROM SYS.SYSREFERENCES R JOIN SYS.SYSOBJECTS O ON (O.ID = R.CONSTID AND O.TYPE = 'F')
   WHERE R.FKEYID = OBJECT_ID('TAMANAGERMG') AND O.NAME = 'FK_TAMANAGE_REFERENCE_TAPOSITI')
ALTER TABLE TAMANAGERMG
   DROP CONSTRAINT FK_TAMANAGE_REFERENCE_TAPOSITI
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('AA10A1')
            AND   TYPE = 'V')
   DROP VIEW AA10A1
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('AA10')
            AND   TYPE = 'U')
   DROP TABLE AA10
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('SSOUSERLOGINIDMAP')
            AND   TYPE = 'U')
   DROP TABLE SSOUSERLOGINIDMAP
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TAACCESSLOG')
            AND   TYPE = 'U')
   DROP TABLE TAACCESSLOG
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TAADMINYAB003SCOPE')
            AND   TYPE = 'U')
   DROP TABLE TAADMINYAB003SCOPE
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TACONFIG')
            AND   TYPE = 'U')
   DROP TABLE TACONFIG
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TACONFIGSYSPATH')
            AND   TYPE = 'U')
   DROP TABLE TACONFIGSYSPATH
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TAMENUPOSITIONYAB003')
            AND   TYPE = 'U')
   DROP TABLE TAMENUPOSITIONYAB003
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TAORGMG')
            AND   TYPE = 'U')
   DROP TABLE TAORGMG
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TASHAREPOSITION')
            AND   TYPE = 'U')
   DROP TABLE TASHAREPOSITION
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TAYAB003SCOPE')
            AND   TYPE = 'U')
   DROP TABLE TAYAB003SCOPE
go


IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('T_YAB003')
            AND   TYPE = 'U')
   DROP TABLE T_YAB003
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TACOMMONMENU')
            AND   TYPE = 'U')
   DROP TABLE TACOMMONMENU
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TALOGINHISTORYLOG')
            AND   TYPE = 'U')
   DROP TABLE TALOGINHISTORYLOG
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TAMENU')
            AND   TYPE = 'U')
   DROP TABLE TAMENU
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TAONLINELOG')
            AND   TYPE = 'U')
   DROP TABLE TAONLINELOG
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TAORG')
            AND   TYPE = 'U')
   DROP TABLE TAORG
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TAORGOPLOG')
            AND   TYPE = 'U')
   DROP TABLE TAORGOPLOG
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TAPOSITION')
            AND   TYPE = 'U')
   DROP TABLE TAPOSITION
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TAPOSITIONAUTHRITY')
            AND   TYPE = 'U')
   DROP TABLE TAPOSITIONAUTHRITY
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TAUSER')
            AND   TYPE = 'U')
   DROP TABLE TAUSER
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TAUSERPOSITION')
            AND   TYPE = 'U')
   DROP TABLE TAUSERPOSITION
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TALOCALCACHEVERSION')
            AND   TYPE = 'U')
   DROP TABLE TALOCALCACHEVERSION
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TAMANAGERMG')
            AND   TYPE = 'U')
   DROP TABLE TAMANAGERMG
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TASERVEREXCEPTIONLOG')
            AND   TYPE = 'U')
   DROP TABLE TASERVEREXCEPTIONLOG
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TADATAACCESSDIMENSION')
            AND   TYPE = 'U')
   DROP TABLE TADATAACCESSDIMENSION
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TACONSOLEMODULE')
            AND   TYPE = 'U')
   DROP TABLE TACONSOLEMODULE
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TACONSOLEMODULELOCATION')
            AND   TYPE = 'U')
   DROP TABLE TACONSOLEMODULELOCATION
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('TACONSOLEMODULEPRIVILEGE')
            AND   TYPE = 'U')
   DROP TABLE TACONSOLEMODULEPRIVILEGE
go

IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('seq')
            AND   TYPE = 'U')
   DROP TABLE seq
go

CREATE TABLE AA10 (
   AAA100               VARCHAR(20)          NOT NULL,
   AAA101               VARCHAR(50)          NOT NULL,
   AAA102               VARCHAR(6)           NOT NULL,
   AAA103               VARCHAR(50)          NOT NULL,
   YAB003               VARCHAR(4)           NOT NULL,
   AAE120               VARCHAR(6)           NOT NULL,
   VER                  NUMERIC(10,0)        NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'AA10代码表',
   'user', @CURRENTUSER, 'table', 'AA10'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'AAA100代码类别',
   'user', @CURRENTUSER, 'table', 'AA10', 'column', 'AAA100'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'AAA101类别名称',
   'user', @CURRENTUSER, 'table', 'AA10', 'column', 'AAA101'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'AAA102代码值',
   'user', @CURRENTUSER, 'table', 'AA10', 'column', 'AAA102'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'AAA103代码名称',
   'user', @CURRENTUSER, 'table', 'AA10', 'column', 'AAA103'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'YAB003经办机构',
   'user', @CURRENTUSER, 'table', 'AA10', 'column', 'YAB003'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'AAE120注销标志',
   'user', @CURRENTUSER, 'table', 'AA10', 'column', 'AAE120'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'VER',
   'user', @CURRENTUSER, 'table', 'AA10', 'column', 'VER'
go

ALTER TABLE AA10
   ADD CONSTRAINT PK_AA10 PRIMARY KEY NONCLUSTERED (AAA100, AAA102)
go

CREATE TABLE SSOUSERLOGINIDMAP (
   LOCALLOGINID         VARCHAR(50)          NOT NULL,
   SSOLOGINID           VARCHAR(50)          NOT NULL,
   SYSTEMID             VARCHAR(6)           NOT NULL,
   EFFECTIVE            CHAR(1)              NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '单点登录系统用户映射',
   'user', @CURRENTUSER, 'table', 'SSOUSERLOGINIDMAP'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '本地用户登录ID',
   'user', @CURRENTUSER, 'table', 'SSOUSERLOGINIDMAP', 'column', 'LOCALLOGINID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'SSO系统用户登录ID',
   'user', @CURRENTUSER, 'table', 'SSOUSERLOGINIDMAP', 'column', 'SSOLOGINID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '系统ID',
   'user', @CURRENTUSER, 'table', 'SSOUSERLOGINIDMAP', 'column', 'SYSTEMID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '有效标识',
   'user', @CURRENTUSER, 'table', 'SSOUSERLOGINIDMAP', 'column', 'EFFECTIVE'
go

ALTER TABLE SSOUSERLOGINIDMAP
   ADD CONSTRAINT PK_SSOUSERLOGINIDMAP PRIMARY KEY NONCLUSTERED (LOCALLOGINID, SSOLOGINID, SYSTEMID)
go

CREATE TABLE TAACCESSLOG (
   LOGID                NUMERIC(15,0)    IDENTITY(1,1)     NOT NULL,
   USERID               NUMERIC(10,0)        NULL,
   POSITIONID           NUMERIC(10,0)        NULL,
   PERMISSIONID         NUMERIC(10,0)        NULL,
   ISPERMISSION         CHAR(1)              NULL,
   ACCESSTIME           DATETIME             NULL,
   URL                  VARCHAR(1024)        NULL,
   SYSFLAG              VARCHAR(50)          NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '功能访问日志',
   'user', @CURRENTUSER, 'table', 'TAACCESSLOG'
go

ALTER TABLE TAACCESSLOG
   ADD CONSTRAINT PK_TAACCESSLOG PRIMARY KEY NONCLUSTERED (LOGID)
go

CREATE TABLE TAADMINYAB003SCOPE (
   POSITIONID           NUMERIC(10,0)        NOT NULL,
   YAB003               VARCHAR(4)           NOT NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '管理员分中心管理范围',
   'user', @CURRENTUSER, 'table', 'TAADMINYAB003SCOPE'
go

ALTER TABLE TAADMINYAB003SCOPE
   ADD CONSTRAINT PK_TAADMINYAB003SCOPE PRIMARY KEY NONCLUSTERED (POSITIONID, YAB003)
go

CREATE TABLE TACONFIG (
   CONFIGID             NUMERIC(10,0)        NOT NULL,
   CONFIGNAME           VARCHAR(100)         NULL,
   CONFIGVALUE          VARCHAR(100)         NULL,
   CONFIGFLAG           VARCHAR(20)          NULL,
   CONFIGDESC           VARCHAR(200)         NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'TACONFIG',
   'user', @CURRENTUSER, 'table', 'TACONFIG'
go

ALTER TABLE TACONFIG
   ADD CONSTRAINT PK_TACONFIG PRIMARY KEY NONCLUSTERED (CONFIGID)
go

CREATE TABLE TACONFIGSYSPATH (
   SERIALID             NUMERIC(10,0)   IDENTITY(1,1)      NOT NULL,
   ID                   VARCHAR(20)          NULL,
   NAME                 VARCHAR(50)          NULL,
   URL                  VARCHAR(100)         NULL,
   PY                   VARCHAR(20)          NULL,
   CURSYSTEM            VARCHAR(1)           NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'TACONFIGSYSPATH',
   'user', @CURRENTUSER, 'table', 'TACONFIGSYSPATH'
go

ALTER TABLE TACONFIGSYSPATH
   ADD CONSTRAINT PK_TACONFIGSYSPATH PRIMARY KEY NONCLUSTERED (SERIALID)
go

CREATE TABLE TAMENUPOSITIONYAB003 (
   MENUID               NUMERIC(10,0)        NOT NULL,
   POSITIONID           NUMERIC(10,0)        NOT NULL,
   YAB003               VARCHAR(4)           NOT NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '功能数据权限',
   'user', @CURRENTUSER, 'table', 'TAMENUPOSITIONYAB003'
go

ALTER TABLE TAMENUPOSITIONYAB003
   ADD CONSTRAINT PK_TAMENUPOSITIONYAB003 PRIMARY KEY NONCLUSTERED (MENUID, POSITIONID, YAB003)
go

CREATE TABLE TAORGMG (
   ORGID                NUMERIC(10,0)        NULL,
   POSITIONID           NUMERIC(10,0)        NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '组织id',
   'user', @CURRENTUSER, 'table', 'TAORGMG', 'column', 'ORGID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '岗位id',
   'user', @CURRENTUSER, 'table', 'TAORGMG', 'column', 'POSITIONID'
go

CREATE TABLE TASHAREPOSITION (
   SPOSITIONID          NUMERIC(10,0)        NOT NULL,
   DPOSITIONID          NUMERIC(10,0)        NOT NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '共享岗位',
   'user', @CURRENTUSER, 'table', 'TASHAREPOSITION'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '岗位id',
   'user', @CURRENTUSER, 'table', 'TASHAREPOSITION', 'column', 'SPOSITIONID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '岗位id',
   'user', @CURRENTUSER, 'table', 'TASHAREPOSITION', 'column', 'DPOSITIONID'
go

ALTER TABLE TASHAREPOSITION
   ADD CONSTRAINT PK_TASHAREPOSITION PRIMARY KEY NONCLUSTERED (SPOSITIONID, DPOSITIONID)
go

CREATE TABLE TAYAB003SCOPE (
   YAB003               VARCHAR(4)             NOT NULL,
   YAB139               VARCHAR(4)           NOT NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '分中心数据权限范围表',
   'user', @CURRENTUSER, 'table', 'TAYAB003SCOPE'
go

ALTER TABLE TAYAB003SCOPE
   ADD CONSTRAINT PK_TAYAB003SCOPE PRIMARY KEY NONCLUSTERED (YAB003, YAB139)
go

CREATE TABLE T_YAB003 (
   YAB003               VARCHAR(6)           NOT NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '经办机构临时表，用于数据权限',
   'user', @CURRENTUSER, 'table', 'T_YAB003'
go

ALTER TABLE T_YAB003
   ADD CONSTRAINT PK_T_YAB003 PRIMARY KEY NONCLUSTERED (YAB003)
go

CREATE TABLE TACOMMONMENU (
   USERID               NUMERIC(10,0)        NOT NULL,
   MENUID               NUMERIC(10,0)        NOT NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '常用菜单',
   'user', @CURRENTUSER, 'table', 'TACOMMONMENU'
go

ALTER TABLE TACOMMONMENU
   ADD CONSTRAINT PK_TACOMMONMENU PRIMARY KEY NONCLUSTERED (USERID, MENUID)
go

CREATE TABLE TALOGINHISTORYLOG (
   LOGID                NUMERIC(15,0)    IDENTITY(1,1)     NOT NULL,
   USERID               NUMERIC(10,0)        NULL,
   LOGINTIME            DATETIME             NULL,
   LOGOUTTIME           DATETIME             NULL,
   CLIENTIP             VARCHAR(200)         NULL,
   SESSIONID            VARCHAR(200)         NULL,
   SERVERIP             VARCHAR(200)         NULL,
   SYSPATH              VARCHAR(50)          NULL
)
go

ALTER TABLE TALOGINHISTORYLOG
   ADD CONSTRAINT PK_TALOGINHISTORYLOG PRIMARY KEY NONCLUSTERED (LOGID)
go

CREATE TABLE TAMENU (
   MENUID               NUMERIC(10,0)     IDENTITY(1,1)    NOT NULL,
   PMENUID              NUMERIC(10,0)        NOT NULL,
   MENUNAME             VARCHAR(60)          NULL,
   URL                  VARCHAR(100)         NULL,
   MENUIDPATH           VARCHAR(1024)         NULL,
   MENUNAMEPATH         VARCHAR(1024)        NULL,
   ICONSKIN             VARCHAR(200)         NULL,
   SELECTIMAGE          VARCHAR(200)         NULL,
   REPORTID             VARCHAR(50)          NULL,
   ACCESSTIMEEL         VARCHAR(200)         NULL,
   EFFECTIVE            CHAR(1)              NOT NULL,
   SECURITYPOLICY       CHAR(1)              NOT NULL,
   ISDISMULTIPOS        CHAR(1)              NOT NULL,
   QUICKCODE            VARCHAR(20)          NULL,
   SORTNO               INT                  NULL,
   RESOURCETYPE         CHAR(2)              NOT NULL,
   MENULEVEL            NUMERIC(10,0)        NULL,
   ISLEAF               CHAR(1)              NULL,
   MENUTYPE             CHAR(1)              NULL,
   ISCACHE              CHAR(1)              NULL,
   SYSPATH              VARCHAR(20)          NULL,
   TYPEFLAG           NUMERIC(1,0)        NULL,
   USEYAB003			CHAR(1)     NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '功能菜单',
   'user', @CURRENTUSER, 'table', 'TAMENU'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '菜单Id',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'MENUID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '父菜单id',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'PMENUID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '功能名称',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'MENUNAME'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '功能地址',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'URL'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '菜单id路径',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'MENUIDPATH'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '菜单名称路径',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'MENUNAMEPATH'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '选择前图片',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'ICONSKIN'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '选择后图片',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'SELECTIMAGE'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '查询报表的报表id',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'REPORTID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '访问限制时间表达式',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'ACCESSTIMEEL'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '有效标志',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'EFFECTIVE'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '安全策略',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'SECURITYPOLICY'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '是否显示多岗',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'ISDISMULTIPOS'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '快捷访问码',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'QUICKCODE'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '排序号',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'SORTNO'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '权限类型（功能权限\按钮权限\表单只读\表单可编辑\表格列只读\表格列可编辑）',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'RESOURCETYPE'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '系统标识',
   'user', @CURRENTUSER, 'table', 'TAMENU', 'column', 'TYPEFLAG'
go

ALTER TABLE TAMENU
   ADD CONSTRAINT PK_TAMENU PRIMARY KEY NONCLUSTERED (MENUID)
go

CREATE TABLE TAONLINELOG (
   LOGID                NUMERIC(15,0)   IDENTITY(1,1)      NOT NULL,
   USERID               NUMERIC(10,0)        NULL,
   LOGINTIME            DATETIME             NULL,
   CURRESOURCE          VARCHAR(1000)        NULL,
   CLIENTIP             VARCHAR(200)         NULL,
   SESSIONID            VARCHAR(200)         NULL,
   SYSPATH              VARCHAR(50)          NULL,
   SERVERIP             VARCHAR(200)         NULL
)
go

ALTER TABLE TAONLINELOG
   ADD CONSTRAINT PK_TAONLINELOG PRIMARY KEY NONCLUSTERED (LOGID)
go

CREATE TABLE TAORG (
   ORGID                NUMERIC(10,0)  IDENTITY(1,1)      NOT NULL,
   PORGID               NUMERIC(10,0)        NULL,
   ORGNAME              VARCHAR(60)          NOT NULL,
   COSTOMNO             VARCHAR(10)          NULL,
   ORGIDPATH            VARCHAR(1024)        NULL,
   ORGNAMEPATH          VARCHAR(1024)        NULL,
   COSTOMNOPATH         VARCHAR(1024)        NULL,
   ORGTYPE              CHAR(2)              NOT NULL,
   SORT                 NUMERIC(2,0)         NULL,
   YAB003               VARCHAR(6)           NULL,
   DIMENSION            CHAR(2)              NULL,
   CREATEUSER           NUMERIC(10,0)        NOT NULL,
   CREATETIME           DATETIME             NOT NULL,
   EFFECTIVE            CHAR(2)              NOT NULL,
   ORGLEVEL             NUMERIC(10,0)        NULL,
   ISLEAF               CHAR(1)              NULL,
   ORGMANAGER           NUMERIC(10,0)        NULL,
   DESTORY              CHAR(1)              NULL,
   TYPEFLAG             NUMERIC(10,0)        NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '组织视图',
   'user', @CURRENTUSER, 'table', 'TAORG'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '组织id',
   'user', @CURRENTUSER, 'table', 'TAORG', 'column', 'ORGID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '组织id',
   'user', @CURRENTUSER, 'table', 'TAORG', 'column', 'PORGID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '名称',
   'user', @CURRENTUSER, 'table', 'TAORG', 'column', 'ORGNAME'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '自定义编码',
   'user', @CURRENTUSER, 'table', 'TAORG', 'column', 'COSTOMNO'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '组织id路径',
   'user', @CURRENTUSER, 'table', 'TAORG', 'column', 'ORGIDPATH'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '组织名称路径',
   'user', @CURRENTUSER, 'table', 'TAORG', 'column', 'ORGNAMEPATH'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '自定义编码路径',
   'user', @CURRENTUSER, 'table', 'TAORG', 'column', 'COSTOMNOPATH'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '组织类型（机构（集团、子公司）、部门、组）',
   'user', @CURRENTUSER, 'table', 'TAORG', 'column', 'ORGTYPE'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '排序号',
   'user', @CURRENTUSER, 'table', 'TAORG', 'column', 'SORT'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '分中心',
   'user', @CURRENTUSER, 'table', 'TAORG', 'column', 'YAB003'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '视图维度',
   'user', @CURRENTUSER, 'table', 'TAORG', 'column', 'DIMENSION'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '创建人',
   'user', @CURRENTUSER, 'table', 'TAORG', 'column', 'CREATEUSER'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '创建时间',
   'user', @CURRENTUSER, 'table', 'TAORG', 'column', 'CREATETIME'
go

ALTER TABLE TAORG
   ADD CONSTRAINT PK_TAORG PRIMARY KEY NONCLUSTERED (ORGID)
go

CREATE TABLE TAORGOPLOG (
   LOGID                NUMERIC(10,0)     IDENTITY(1,1)    NOT NULL,
   BATCHNO              VARCHAR(10)          NULL,
   OPTYPE               CHAR(2)              NULL,
   INFLUENCEBODYTYPE    CHAR(2)              NULL,
   INFLUENCEBODY        VARCHAR(10)          NULL,
   OPBODY               CHAR(2)              NULL,
   OPSUBJEKT            VARCHAR(10)          NULL,
   CHANGCONTENT         VARCHAR(2048)        NULL,
   OPTIME               DATETIME             NOT NULL,
   OPUSER               VARCHAR(10)          NOT NULL,
   OPPOSITION           VARCHAR(10)          NOT NULL,
   ISPERMISSION         VARCHAR(1)           NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '组织及权限操作日志',
   'user', @CURRENTUSER, 'table', 'TAORGOPLOG'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '日志id',
   'user', @CURRENTUSER, 'table', 'TAORGOPLOG', 'column', 'LOGID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '操作批次号',
   'user', @CURRENTUSER, 'table', 'TAORGOPLOG', 'column', 'BATCHNO'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '操作类型（新增、编辑、删除、授权、回收权限）',
   'user', @CURRENTUSER, 'table', 'TAORGOPLOG', 'column', 'OPTYPE'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '影响主体类型（组织、人员、岗位、角色、权限资源）',
   'user', @CURRENTUSER, 'table', 'TAORGOPLOG', 'column', 'INFLUENCEBODYTYPE'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '影响主体',
   'user', @CURRENTUSER, 'table', 'TAORGOPLOG', 'column', 'INFLUENCEBODY'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '操作主体类型（人员、组织、岗位、角色、权限资源）',
   'user', @CURRENTUSER, 'table', 'TAORGOPLOG', 'column', 'OPBODY'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '操作主体',
   'user', @CURRENTUSER, 'table', 'TAORGOPLOG', 'column', 'OPSUBJEKT'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '主体变更内容',
   'user', @CURRENTUSER, 'table', 'TAORGOPLOG', 'column', 'CHANGCONTENT'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '经办时间',
   'user', @CURRENTUSER, 'table', 'TAORGOPLOG', 'column', 'OPTIME'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '经办人',
   'user', @CURRENTUSER, 'table', 'TAORGOPLOG', 'column', 'OPUSER'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '经办岗位',
   'user', @CURRENTUSER, 'table', 'TAORGOPLOG', 'column', 'OPPOSITION'
go

ALTER TABLE TAORGOPLOG
   ADD CONSTRAINT PK_TAORGOPLOG PRIMARY KEY NONCLUSTERED (LOGID)
go

CREATE TABLE TAPOSITION (
   POSITIONID           NUMERIC(10,0)   IDENTITY(1,1)      NOT NULL,
   ORGID                NUMERIC(10,0)        NOT NULL,
   POSITIONNAME         VARCHAR(60)          NOT NULL,
   POSITIONTYPE         CHAR(1)              NOT NULL,
   CREATEPOSITIONID     NUMERIC(10,0)        NOT NULL,
   ORGIDPATH            VARCHAR(1024)        NULL,
   ORGNAMEPATH          VARCHAR(1024)        NULL,
   VALIDTIME            DATETIME             NULL,
   CREATEUSER           NUMERIC(10,0)        NOT NULL,
   CREATETIME           DATETIME             NOT NULL,
   EFFECTIVE            CHAR(1)              NOT NULL,
   ISADMIN              CHAR(1)              NULL,
   ISSHARE              CHAR(1)              NULL,
   ISCOPY               CHAR(1)              NULL,
   TYPEFLAG           NUMERIC(1,0)   NULL,
   POSITIONCATEGORY      VARCHAR(2) NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '岗位',
   'user', @CURRENTUSER, 'table', 'TAPOSITION'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '岗位id',
   'user', @CURRENTUSER, 'table', 'TAPOSITION', 'column', 'POSITIONID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '组织id',
   'user', @CURRENTUSER, 'table', 'TAPOSITION', 'column', 'ORGID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '岗位名称',
   'user', @CURRENTUSER, 'table', 'TAPOSITION', 'column', 'POSITIONNAME'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '岗位类型（个人专属岗位/公有岗位）',
   'user', @CURRENTUSER, 'table', 'TAPOSITION', 'column', 'POSITIONTYPE'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '创建人使用的岗位',
   'user', @CURRENTUSER, 'table', 'TAPOSITION', 'column', 'CREATEPOSITIONID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '只真对委派生成的岗位',
   'user', @CURRENTUSER, 'table', 'TAPOSITION', 'column', 'VALIDTIME'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '创建人',
   'user', @CURRENTUSER, 'table', 'TAPOSITION', 'column', 'CREATEUSER'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '创建时间',
   'user', @CURRENTUSER, 'table', 'TAPOSITION', 'column', 'CREATETIME'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '有效标志',
   'user', @CURRENTUSER, 'table', 'TAPOSITION', 'column', 'EFFECTIVE'
go
DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '岗位类别',
   'user', @CURRENTUSER, 'table', 'TAPOSITION', 'column', 'POSITIONCATEGORY'
go

ALTER TABLE TAPOSITION
   ADD CONSTRAINT PK_TAPOSITION PRIMARY KEY NONCLUSTERED (POSITIONID)
go

CREATE TABLE TAPOSITIONAUTHRITY (
   POSITIONID           NUMERIC(10,0)        NOT NULL,
   MENUID               NUMERIC(10,0)        NOT NULL,
   USEPERMISSION        CHAR(1)              NULL,
   REPERMISSION         CHAR(1)              NULL,
   REAUTHRITY           CHAR(1)              NULL,
   CREATEUSER           NUMERIC(10,0)        NOT NULL,
   CREATETIME           DATETIME             NOT NULL,
   EFFECTTIME           DATETIME             NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '岗位权限表',
   'user', @CURRENTUSER, 'table', 'TAPOSITIONAUTHRITY'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '岗位id',
   'user', @CURRENTUSER, 'table', 'TAPOSITIONAUTHRITY', 'column', 'POSITIONID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '菜单Id',
   'user', @CURRENTUSER, 'table', 'TAPOSITIONAUTHRITY', 'column', 'MENUID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '使用权限',
   'user', @CURRENTUSER, 'table', 'TAPOSITIONAUTHRITY', 'column', 'USEPERMISSION'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '授权别人使用权限',
   'user', @CURRENTUSER, 'table', 'TAPOSITIONAUTHRITY', 'column', 'REPERMISSION'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '授权别人授权权限',
   'user', @CURRENTUSER, 'table', 'TAPOSITIONAUTHRITY', 'column', 'REAUTHRITY'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '创建人',
   'user', @CURRENTUSER, 'table', 'TAPOSITIONAUTHRITY', 'column', 'CREATEUSER'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '创建时间',
   'user', @CURRENTUSER, 'table', 'TAPOSITIONAUTHRITY', 'column', 'CREATETIME'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '有效时间',
   'user', @CURRENTUSER, 'table', 'TAPOSITIONAUTHRITY', 'column', 'EFFECTTIME'
go

ALTER TABLE TAPOSITIONAUTHRITY
   ADD CONSTRAINT PK_TAPOSITIONAUTHRITY PRIMARY KEY NONCLUSTERED (POSITIONID, MENUID)
go

CREATE TABLE TAUSER (
   USERID               NUMERIC(10,0)    IDENTITY(1,1)     NOT NULL,
   NAME                 VARCHAR(50)          NOT NULL,
   SEX                  CHAR(1)              NULL,
   LOGINID              VARCHAR(10)          NOT NULL,
   PASSWORD             VARCHAR(50)          NOT NULL,
   PASSWORDFAULTNUM     NUMERIC(8,0)         NULL,
   PWDLASTMODIFYDATE    DATETIME             NULL,
   ISLOCK               CHAR(1)              NULL,
   SORT                 NUMERIC(2,0)         NULL,
   EFFECTIVE            CHAR(1)              NOT NULL,
   TEL                  VARCHAR(15)          NULL,
   CREATEUSER           NUMERIC(10,0)        NOT NULL,
   CREATETIME           DATETIME             NOT NULL,
   DIRECTORGID          NUMERIC(10,0)        NULL,
   DESTORY              CHAR(1)              NULL,
   TYPEFLAG             NUMERIC(1,0)        NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '人员',
   'user', @CURRENTUSER, 'table', 'TAUSER'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '人员id',
   'user', @CURRENTUSER, 'table', 'TAUSER', 'column', 'USERID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '姓名',
   'user', @CURRENTUSER, 'table', 'TAUSER', 'column', 'NAME'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '性别',
   'user', @CURRENTUSER, 'table', 'TAUSER', 'column', 'SEX'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '登陆账号',
   'user', @CURRENTUSER, 'table', 'TAUSER', 'column', 'LOGINID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '密码',
   'user', @CURRENTUSER, 'table', 'TAUSER', 'column', 'PASSWORD'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '口令错误次数',
   'user', @CURRENTUSER, 'table', 'TAUSER', 'column', 'PASSWORDFAULTNUM'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '口令最后修改时间',
   'user', @CURRENTUSER, 'table', 'TAUSER', 'column', 'PWDLASTMODIFYDATE'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '锁定标志',
   'user', @CURRENTUSER, 'table', 'TAUSER', 'column', 'ISLOCK'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '排序号',
   'user', @CURRENTUSER, 'table', 'TAUSER', 'column', 'SORT'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '有效标志',
   'user', @CURRENTUSER, 'table', 'TAUSER', 'column', 'EFFECTIVE'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '联系电话',
   'user', @CURRENTUSER, 'table', 'TAUSER', 'column', 'TEL'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '创建人',
   'user', @CURRENTUSER, 'table', 'TAUSER', 'column', 'CREATEUSER'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '创建时间',
   'user', @CURRENTUSER, 'table', 'TAUSER', 'column', 'CREATETIME'
go

ALTER TABLE TAUSER
   ADD CONSTRAINT PK_TAUSER PRIMARY KEY NONCLUSTERED (USERID)
go

CREATE TABLE TAUSERPOSITION (
   USERID               NUMERIC(10,0)        NOT NULL,
   POSITIONID           NUMERIC(10,0)        NOT NULL,
   MAINPOSITION         CHAR(1)              NOT NULL,
   CREATEUSER           NUMERIC(10,0)        NOT NULL,
   CREATETIME           DATETIME             NOT NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '人员与岗位关系表',
   'user', @CURRENTUSER, 'table', 'TAUSERPOSITION'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '人员id',
   'user', @CURRENTUSER, 'table', 'TAUSERPOSITION', 'column', 'USERID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '岗位id',
   'user', @CURRENTUSER, 'table', 'TAUSERPOSITION', 'column', 'POSITIONID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '默认岗位',
   'user', @CURRENTUSER, 'table', 'TAUSERPOSITION', 'column', 'MAINPOSITION'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '创建人',
   'user', @CURRENTUSER, 'table', 'TAUSERPOSITION', 'column', 'CREATEUSER'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '创建时间',
   'user', @CURRENTUSER, 'table', 'TAUSERPOSITION', 'column', 'CREATETIME'
go

ALTER TABLE TAUSERPOSITION
   ADD CONSTRAINT PK_TAUSERPOSITION PRIMARY KEY NONCLUSTERED (USERID, POSITIONID)
go

CREATE TABLE TALOCALCACHEVERSION (
   VERSION              INT                  NULL,
   CODETYPE             VARCHAR(20)          NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '本地缓存码表版本号',
   'user', @CURRENTUSER, 'table', 'TALOCALCACHEVERSION'
go

CREATE TABLE TAMANAGERMG (
   ORGID                NUMERIC(10,0)        NOT NULL,
   POSITIONID           NUMERIC(10,0)        NOT NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '组织负责人（副职）管理表',
   'user', @CURRENTUSER, 'table', 'TAMANAGERMG'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '组织id',
   'user', @CURRENTUSER, 'table', 'TAMANAGERMG', 'column', 'ORGID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '岗位id',
   'user', @CURRENTUSER, 'table', 'TAMANAGERMG', 'column', 'POSITIONID'
go

ALTER TABLE TAMANAGERMG
   ADD CONSTRAINT PK_TAMANAGERMG PRIMARY KEY NONCLUSTERED (ORGID, POSITIONID)
go

CREATE TABLE TASERVEREXCEPTIONLOG (
   ID                   VARCHAR(32)          NOT NULL,
   IPADDRESS            VARCHAR(255)         NULL,
   TYPE                 VARCHAR(255)         NULL,
   CONTENT              NTEXT                NULL,
   TIME                 DATETIME             NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '系统异常日志表',
   'user', @CURRENTUSER, 'table', 'TASERVEREXCEPTIONLOG'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   'id',
   'user', @CURRENTUSER, 'table', 'TASERVEREXCEPTIONLOG', 'column', 'ID'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '服务器ip地址',
   'user', @CURRENTUSER, 'table', 'TASERVEREXCEPTIONLOG', 'column', 'IPADDRESS'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '异常类型',
   'user', @CURRENTUSER, 'table', 'TASERVEREXCEPTIONLOG', 'column', 'TYPE'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '异常内容',
   'user', @CURRENTUSER, 'table', 'TASERVEREXCEPTIONLOG', 'column', 'CONTENT'
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '报错时间',
   'user', @CURRENTUSER, 'table', 'TASERVEREXCEPTIONLOG', 'column', 'TIME'
go

ALTER TABLE TASERVEREXCEPTIONLOG
   ADD CONSTRAINT PK_TASERVEREXCEPTIONLOG PRIMARY KEY NONCLUSTERED (ID)
go

CREATE TABLE TADATAACCESSDIMENSION (
   DIMENSIONID          NUMERIC(10)    IDENTITY(1,1)       NOT NULL,
   POSITIONID           NUMERIC(10)          NULL,
   MENUID               NUMERIC(10)          NULL,
   DIMENSIONTYPE        VARCHAR(2)           NULL,
   DIMENSIONPERMISSIONID VARCHAR(20)          NULL,
   ALLPERMISSION        VARCHAR(1)           NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '多维度数据权限表',
   'user', @CURRENTUSER, 'table', 'TADATAACCESSDIMENSION'
go

ALTER TABLE TADATAACCESSDIMENSION
   ADD CONSTRAINT PK_TADATAACCESSDIMENSION PRIMARY KEY NONCLUSTERED (DIMENSIONID)
go

CREATE TABLE TACONSOLEMODULE(
	MODULE_ID NUMERIC(20, 0) IDENTITY(1,1) NOT NULL,
	MODULE_NAME VARCHAR(100) NOT NULL,
	MODULE_URL VARCHAR(200) NOT NULL,
		MODULE_DEFAULT VARCHAR(1) DEFAULT 1 NOT NULL,
		MODULE_HEIGHT VARCHAR(10) DEFAULT 200 NOT NULL,
		MODULE_STA VARCHAR(1) DEFAULT 1 NOT NULL
	) 

go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '控制台',
   'user', @CURRENTUSER, 'table', 'TACONSOLEMODULE'
go

ALTER TABLE TACONSOLEMODULE
   ADD CONSTRAINT PK_TACONSOLEMODULE PRIMARY KEY NONCLUSTERED (MODULE_ID)
go

CREATE TABLE TACONSOLEMODULELOCATION(
	MARK VARCHAR(20) NULL,
	POSITIONID NUMERIC(10, 0) NULL,
	LOCATION VARCHAR(1000) NULL
)

go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '控制台模块位置',
   'user', @CURRENTUSER, 'table', 'TACONSOLEMODULELOCATION'
   
go

CREATE TABLE TACONSOLEMODULEPRIVILEGE(
	POSITIONID NUMERIC(10, 0) NOT NULL,
	MODULEID NUMERIC(10, 0) NOT NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '控制台模块权限',
   'user', @CURRENTUSER, 'table', 'TACONSOLEMODULEPRIVILEGE'
   
 go
CREATE TABLE SERVERADDRESS(
	ADDRESS VARCHAR(200) NOT NULL,
	CANUSE VARCHAR(1) NULL
)
go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '集群地址',
   'user', @CURRENTUSER, 'table', 'SERVERADDRESS'
   
 go
 
 CREATE TABLE SEQ(
 	NAME VARCHAR(50) NOT NULL,
 	VAL NUMERIC(10,0)
 )
 go

DECLARE @CURRENTUSER SYSNAME
SELECT @CURRENTUSER = USER_NAME()
EXECUTE SP_ADDEXTENDEDPROPERTY 'MS_Description', 
   '序列',
   'user', @CURRENTUSER, 'table', 'SEQ'
   
 go
   
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('MENUTYPE', '菜单类型', '0', '通用菜单', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('MENUTYPE', '菜单类型', '1', '系统管理菜单', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('MENUTYPE', '菜单类型', '2', '业务功能菜单', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('ORGTYPE', '组织类型', '04', '组', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POSITIONTYPE', '岗位类型', '1', '公有岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POSITIONTYPE', '岗位类型', '2', '个人岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POSITIONTYPE', '岗位类型', '3', '委派岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('SEX', '性别', '1', '男', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('SEX', '性别', '2', '女', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('SEX', '性别', '0', '无', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('ORGTYPE', '组织类型', '01', '机构', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('ORGTYPE', '组织类型', '02', '部门', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('EFFECTIVE', '有效标志', '0', '有效', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('EFFECTIVE', '有效标志', '1', '无效', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('YESORNO', '是否', '0', '是', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('YESORNO', '是否', '1', '否', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POLICY', '安全策略', '1', '要认证要显示', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POLICY', '安全策略', '2', '要认证不显示', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POLICY', '安全策略', '3', '不认证不显示', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POLICY', '安全策略', '4', '不认证要显示', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '01', '新增组织', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '02', '编辑组织', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '03', '禁用组织', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '04', '新增人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '05', '编辑人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '06', '禁用人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '07', '密码重置', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '08', '赋予岗位给人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '09', '设置主岗位给人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '10', '新增岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '11', '编辑岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '12', '禁用岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '13', '赋予岗位使用权限', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '14', '回收岗位使用权限', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '15', '启用岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '16', '启用人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '17', '启用组织', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '18', '删除组织', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '19', '赋予岗位授权别人使用权限', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '20', '回收岗位授权别人使用权限', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '21', '赋予岗位授权别人授权权限', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '22', '回收岗位授权别人授权权限', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '23', '删除管理员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '24', '新增管理员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '25', '删除岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '26', '删除人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPOBJTYPE', '操作对象类型', '01', '组织', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPOBJTYPE', '操作对象类型', '02', '人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPOBJTYPE', '操作对象类型', '03', '岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPOBJTYPE', '操作对象类型', '04', '权限', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('YAB003', '分中心', '9999', '9999', '9999', '0', 0);
INSERT INTO AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER) VALUES ('POSITIONCATEGORY', '岗位类别', '01', '业务岗', '9999', '0', 0);
INSERT INTO AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER) VALUES ('POSITIONCATEGORY', '岗位类别', '02', '稽核岗', '9999', '0', 0);

INSERT INTO TACONFIGSYSPATH (ID, NAME, URL, PY, CURSYSTEM) values('sysmg','系统管理','http://127.0.0.1:8080/ta3/','xtgl','0');
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('0','银海软件',NULL,'1','银海软件','tree-apply',NULL,NULL,NULL,'0','1','0',NULL,'0','01','1','1','0',NULL,'sysmg',0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('1','系统管理',NULL,'1/2','银海软件/系统管理','tree-apply',NULL,NULL,NULL,'0','1','0',NULL,'0','01','2','1','1',NULL,'sysmg',0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('2','菜单管理','sysapp/menuMgAction.do','1/2/3','银海软件/系统管理/菜单管理','tree-setting',NULL,NULL,NULL,'0','1','0',NULL,'0','01','3','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('2','组织权限管理',NULL,'1/2/4','银海软件/系统管理/组织权限管理','tree-view-refresh',NULL,NULL,NULL,'0','1','1',NULL,'1','01','3','1','1',NULL,'sysmg',0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('4','用户功能权限管理','org/position/personalPositionMgAction.do','1/2/4/5','银海软件/系统管理/组织权限管理/用户功能权限管理','tree-user',NULL,NULL,NULL,'0','1','1',NULL,'3','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('4','岗位及权限管理','org/position/positionMgAction.do','1/2/4/6','银海软件/系统管理/组织权限管理/岗位及权限管理','tree-users',NULL,NULL,NULL,'0','1','1',NULL,'4','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('4','管理员管理','org/position/adminMgAction.do','1/2/4/7','银海软件/系统管理/组织权限管理/管理员管理','tree-userm',NULL,NULL,NULL,'0','1','1',NULL,'2','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG) values('4','经办机构数据权限管理','org/position/dataAccessDimensionManagementAction.do','1/2/4/8','银海软件/系统管理/组织权限管理/经办机构数据权限管理','tree-database',NULL,NULL,'','0','1','1',NULL,'10','01','4','0','1',NULL,'sysmg',NULL,NULL);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('4','用户管理','org/userMgAction.do','1/2/4/9','银海软件/系统管理/组织权限管理/用户管理','tree-group',NULL,NULL,NULL,'0','1','1',NULL,'1','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('4','组织管理','org/orgMgAction.do','1/2/4/10','银海软件/系统管理/组织权限管理/组织管理','tree-organisation',NULL,NULL,NULL,'0','1','1',NULL,'0','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('4','用户岗位设置','org/position/positionSettingMgAction.do','1/2/4/11','银海软件/系统管理/组织权限管理/用户岗位设置','tree-preferences-system',NULL,NULL,NULL,'0','1','1',NULL,'5','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('4','功能权限代理','org/position/delegatePositionAction.do','1/2/4/12','银海软件/系统管理/组织权限管理/功能权限代理','tree-mail-send-receive',NULL,NULL,NULL,'0','1','1',NULL,'6','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('4','相似权限授权','org/position/similarAuthorityAction.do','1/2/4/13','银海软件/系统管理/组织权限管理/相似权限授权','tree-view-refresh',NULL,NULL,NULL,'0','1','1',NULL,'7','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('2','工作台管理','','1/2/14','银海软件/系统管理/工作台管理','tree-destop','','','','0','1','1','','2','01','3','1','1','','sysmg',0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('14','工作台模块管理','sysapp/moduleMainAction.do','1/2/14/15','银海软件/系统管理/工作台管理/工作台模块管理','tree-menu','','','','0','1','1','','0','01','4','0','1','','sysmg',0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('14','模块授权管理','sysapp/moduleMainAction!toGrant.do','1/2/14/16','银海软件/系统管理/工作台管理/模块授权管理','tree-star','','','','0','1','1','','1','01','4','0','1','','sysmg',0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('2','系统参数管理','sysapp/configMgAction.do','1/2/17','银海软件/系统管理/系统参数管理','tree-preferences-system',NULL,NULL,NULL,'0','1','0',NULL,'3','01','3','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('2', '代码表查看', 'sysapp/appCodeMainAction.do', '1/2/19', '银海软件/系统管理/代码表查看', 'tree-system-search', NULL, NULL, NULL, '0', '1', '1', NULL, 3, '01', 3, '0', '1', NULL, 'sysmg', 0);
INSERT INTO TAMENU (PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('2', '分布式管理', 'sysapp/serverAddressAction.do', '1/2/19', '银海软件/系统管理/分布式管理', 'btn-setting', NULL, NULL, NULL, '0', '1', '1', NULL, 4, '01', 3, '0', '1', NULL, 'sysmg', 0);
INSERT INTO TAMENU (PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG) values ( '4', '批量导入组织人员', 'org/upload/uploadOrgUserAction.do', '1/2/4/20', '银海软件/系统管理/组织权限管理/批量导入组织人员', 'tree-edit-redo', '', '', '', '0', '1', '1', '', 9, '01', 4, '0', '1', '', 'sysmg', '', 0);
INSERT INTO TAMENU (PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG) values ( '2', '系统Exception日志', 'sysapp/serverExeceptionLogAction.do', '1/2/21', '银海软件/系统管理/系统Exception日志', 'tree-document-new', NULL, NULL, NULL, '0', '1', '1', NULL, 6, '01', 3, '0', '1', NULL, 'sysmg', NULL, NULL);
INSERT INTO TAORG (PORGID,ORGNAME,COSTOMNO,ORGIDPATH,ORGNAMEPATH,COSTOMNOPATH,ORGTYPE,SORT,YAB003,DIMENSION,CREATEUSER,CREATETIME,EFFECTIVE,ORGLEVEL,ISLEAF,TYPEFLAG) VALUES (NULL,'银海软件','1','1','银海软件','0','01',0,'9999',NULL,0,GETDATE(),'0',0,'0',0);
INSERT INTO TAUSER (NAME,SEX,LOGINID,PASSWORD,PASSWORDFAULTNUM,PWDLASTMODIFYDATE,ISLOCK,SORT,EFFECTIVE,TEL,CREATEUSER,CREATETIME,DIRECTORGID,TYPEFLAG) VALUES ('超级管理员','1','developer','UKsyhLAzBwGwLLCq8TNDxQ==',0,GETDATE(),'0',0,'0','0',1,GETDATE(),1,0);
INSERT INTO TAPOSITION (ORGID,POSITIONNAME,POSITIONTYPE,CREATEPOSITIONID,ORGIDPATH,ORGNAMEPATH,VALIDTIME,CREATEUSER,CREATETIME,EFFECTIVE,ISADMIN,TYPEFLAG) VALUES (1,'超级管理员','1',1,'1','银海软件',NULL,1,GETDATE(),'0','1',0);
INSERT INTO TAUSERPOSITION (USERID,POSITIONID,MAINPOSITION,CREATEUSER,CREATETIME) VALUES (1,1,'1',1,GETDATE());
INSERT INTO SEQ(NAME,VAL) VALUES('SEQ_DEFAULT',100000000);
INSERT INTO TALOCALCACHEVERSION(VERSION, CODETYPE) VALUES (1,'');

go

CREATE VIEW AA10A1 AS
SELECT
   AAA100,
   AAA101,
   AAA102,
   AAA103,
   YAB003,
   AAE120,
   VER
FROM
   AA10
go

ALTER TABLE TAORGMG
   ADD CONSTRAINT FK_TAORGMG_REFERENCE_TAORG FOREIGN KEY (ORGID)
      REFERENCES TAORG (ORGID)
go

ALTER TABLE TAORGMG
   ADD CONSTRAINT FK_TAORGMG_REFERENCE_TAPOSITI FOREIGN KEY (POSITIONID)
      REFERENCES TAPOSITION (POSITIONID)
go

ALTER TABLE TASHAREPOSITION
   ADD CONSTRAINT FK_TASHAREP_REFERENCE_TAPOSITI FOREIGN KEY (SPOSITIONID)
      REFERENCES TAPOSITION (POSITIONID)
go

ALTER TABLE TASHAREPOSITION
   ADD CONSTRAINT FK_TASHAREP_REFERENCE_TAPOSITI FOREIGN KEY (DPOSITIONID)
      REFERENCES TAPOSITION (POSITIONID)
go

ALTER TABLE TACOMMONMENU
   ADD CONSTRAINT FK_TACOMMON_REFERENCE_TAUSER FOREIGN KEY (USERID)
      REFERENCES TAUSER (USERID)
go

ALTER TABLE TACOMMONMENU
   ADD CONSTRAINT FK_TACOMMON_REFERENCE_TAMENU FOREIGN KEY (MENUID)
      REFERENCES TAMENU (MENUID)
go

ALTER TABLE TAORG
   ADD CONSTRAINT FK_TAORG_REFERENCE_TAORG FOREIGN KEY (PORGID)
      REFERENCES TAORG (ORGID)
go

ALTER TABLE TAPOSITION
   ADD CONSTRAINT FK_TAPOSITI_RELATIONS_TAORG FOREIGN KEY (ORGID)
      REFERENCES TAORG (ORGID)
go

ALTER TABLE TAPOSITIONAUTHRITY
   ADD CONSTRAINT FK_TAPOSITI_REFERENCE_TAMENU FOREIGN KEY (MENUID)
      REFERENCES TAMENU (MENUID)
         ON DELETE CASCADE
go

ALTER TABLE TAPOSITIONAUTHRITY
   ADD CONSTRAINT FK_TAPOSITI_RELATIONS_TAPOSITI FOREIGN KEY (POSITIONID)
      REFERENCES TAPOSITION (POSITIONID)
go

ALTER TABLE TAUSERPOSITION
   ADD CONSTRAINT FK_TAUSERPO_RELATIONS_TAPOSITI FOREIGN KEY (POSITIONID)
      REFERENCES TAPOSITION (POSITIONID)
go

ALTER TABLE TAUSERPOSITION
   ADD CONSTRAINT FK_TAUSERPO_RELATIONS_TAUSER FOREIGN KEY (USERID)
      REFERENCES TAUSER (USERID)
go

ALTER TABLE TAMANAGERMG
   ADD CONSTRAINT FK_TAMANAGE_REFERENCE_TAORG FOREIGN KEY (ORGID)
      REFERENCES TAORG (ORGID)
go

ALTER TABLE TAMANAGERMG
   ADD CONSTRAINT FK_TAMANAGE_REFERENCE_TAPOSITI FOREIGN KEY (POSITIONID)
      REFERENCES TAPOSITION (POSITIONID)
go
