ALTER TABLE TAORGMG
   DROP CONSTRAINT FK_REFERENCE_8;
ALTER TABLE TAORGMG
   DROP CONSTRAINT FK_REFERENCE_9;
ALTER TABLE TAORG
   DROP CONSTRAINT FK_REFERENCE_6;
ALTER TABLE TAPOSITION
   DROP CONSTRAINT FK_RELATIONSHIP_5;
ALTER TABLE TAPOSITIONAUTHRITY
   DROP CONSTRAINT FK_REFERENCE_7;
ALTER TABLE TAPOSITIONAUTHRITY
   DROP CONSTRAINT FK_RELATIONSHIP_11;
ALTER TABLE TAUSERPOSITION
   DROP CONSTRAINT FK_RELATIONSHIP_10;
ALTER TABLE TAUSERPOSITION
   DROP CONSTRAINT FK_RELATIONSHIP_9;
   
DROP view AA10A1;

DROP TABLE  AA10 CASCADE CONSTRAINTS;

DROP TABLE  TACONFIG CASCADE CONSTRAINTS;

DROP TABLE  TACONFIGSYSPATH CASCADE CONSTRAINTS;

DROP TABLE TAORGMG CASCADE CONSTRAINTS;

DROP TABLE TASHAREPOSITION CASCADE CONSTRAINTS;

DROP TABLE TAMANAGERMG CASCADE CONSTRAINTS;

DROP TABLE TAMENU CASCADE CONSTRAINTS;

DROP TABLE TAORG CASCADE CONSTRAINTS;

DROP TABLE TAORGOPLOG CASCADE CONSTRAINTS;

DROP TABLE TAPOSITION CASCADE CONSTRAINTS;

DROP TABLE TAPOSITIONAUTHRITY CASCADE CONSTRAINTS;

DROP TABLE TAUSER CASCADE CONSTRAINTS;

DROP TABLE TAUSERPOSITION CASCADE CONSTRAINTS;

DROP TABLE TAACCESSLOG CASCADE CONSTRAINTS;

DROP TABLE TAMENUPOSITIONYAB003 CASCADE CONSTRAINTS;

DROP TABLE TAADMINYAB003SCOPE CASCADE CONSTRAINTS;

DROP TABLE TACOMMONMENU CASCADE CONSTRAINTS;

DROP TABLE TAYAB003SCOPE CASCADE CONSTRAINTS;

DROP TABLE SERVERADDRESS CASCADE CONSTRAINTS;

DROP TABLE TACONSOLEMODULE CASCADE CONSTRAINTS;

DROP TABLE TACONSOLEMODULELOCATION CASCADE CONSTRAINTS;

DROP TABLE TACONSOLEMODULEPRIVILEGE CASCADE CONSTRAINTS;

DROP TABLE TAONLINELOG CASCADE CONSTRAINTS;

DROP TABLE TALOGINHISTORYLOG CASCADE CONSTRAINTS;

DROP SEQUENCE HIBERNATE_SEQUENCE;

DROP SEQUENCE SEQ_DEFAULT;

DROP TABLE TASERVEREXCEPTIONLOG CASCADE CONSTRAINTS;

create sequence HIBERNATE_SEQUENCE
minvalue 100000
maxvalue 1000000000
start with 110000
increment by 1;

create sequence SEQ_DEFAULT
minvalue 100000
maxvalue 1000000000
start with 110000
increment by 1;


/*==============================================================*/
/* Table: TASERVEREXCEPTIONLOG                                                */
/*==============================================================*/
CREATE TABLE TASERVEREXCEPTIONLOG 
(
   ID                   VARCHAR2(32)         NOT NULL,
   IPADDRESS            VARCHAR2(255),
   TYPE                 VARCHAR2(255),
   CONTENT              BLOB,
   TIME                 DATE
);

COMMENT ON TABLE TASERVEREXCEPTIONLOG IS '系统异常日志表';
COMMENT ON COLUMN TASERVEREXCEPTIONLOG.ID IS 'id';
COMMENT ON COLUMN TASERVEREXCEPTIONLOG.IPADDRESS IS '服务器ip地址';
COMMENT ON COLUMN TASERVEREXCEPTIONLOG.TYPE IS '异常类型';
COMMENT ON COLUMN TASERVEREXCEPTIONLOG.CONTENT IS '异常内容';
COMMENT ON COLUMN TASERVEREXCEPTIONLOG.TIME IS '报错时间';
ALTER TABLE TASERVEREXCEPTIONLOG  ADD CONSTRAINT PK_TASERVEREXCEPTIONLOG PRIMARY KEY (ID);


/*==============================================================*/
/* Table: AA10                                                  */
/*==============================================================*/
CREATE TABLE AA10
(
   AAA100               VARCHAR2(20) NOT NULL ,
   AAA101               VARCHAR2(50) NOT NULL ,
   AAA102               VARCHAR2(6) NOT NULL ,
   AAA103               VARCHAR2(50) NOT NULL ,
   YAB003               VARCHAR2(4) NOT NULL ,
   AAE120               VARCHAR2(6) NOT NULL ,
   VER                  NUMBER(10,0) ,
   constraint PK_AA10 primary key (AAA100, AAA102)
);

COMMENT ON TABLE AA10 IS 'AA10代码表';
COMMENT ON COLUMN AA10.AAA100 IS 'AAA100代码类别';
COMMENT ON COLUMN AA10.AAA101 IS 'AAA102代码值';
COMMENT ON COLUMN AA10.AAA102 IS 'AAA102代码值';
COMMENT ON COLUMN AA10.AAA103 IS 'AAA103代码名称';
COMMENT ON COLUMN AA10.YAB003 IS 'YAB003经办机构';
COMMENT ON COLUMN AA10.AAE120 IS 'AAE120注销标志';

/*==============================================================*/
/* Table: TACONFIG                                                  */
/*==============================================================*/
CREATE TABLE TACONFIG (
  CONFIGID NUMBER(10,0) NOT NULL,
  CONFIGNAME VARCHAR2(100) NOT NULL,
  CONFIGVALUE VARCHAR2(1024) ,
  CONFIGTYPE VARCHAR2(1024) ,
  CONFIGFLAG VARCHAR2(20) NOT NULL,
  CONFIGDESC VARCHAR2(200),
  CONSTRAINT PK_TACONFIG PRIMARY KEY (CONFIGID)
);
COMMENT ON TABLE TACONFIG IS '系统配置表';
COMMENT ON COLUMN TACONFIG.CONFIGID IS '配置项ID';
COMMENT ON COLUMN TACONFIG.CONFIGNAME IS '配置项名称';
COMMENT ON COLUMN TACONFIG.CONFIGVALUE IS '配置项内容';
COMMENT ON COLUMN TACONFIG.CONFIGTYPE IS '是否系统参数';
COMMENT ON COLUMN TACONFIG.CONFIGFLAG IS '系统标识';
COMMENT ON COLUMN TACONFIG.CONFIGDESC IS '参数说明';

/*==============================================================*/
/* Table: TACONFIGSYSPATH                                                */
/*==============================================================*/
CREATE TABLE TACONFIGSYSPATH (
  SERIALID NUMBER(10,0) NOT NULL,
  ID VARCHAR2(20) NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  URL VARCHAR2(100) NOT NULL,
  PY VARCHAR2(20) ,
  CURSYSTEM VARCHAR2(1) NOT NULL,
  PRIMARY KEY (SERIALID)
);
COMMENT ON TABLE TACONFIGSYSPATH IS '系统路径配置表';
COMMENT ON COLUMN TACONFIGSYSPATH.SERIALID IS '流水号';
COMMENT ON COLUMN TACONFIGSYSPATH.ID IS '系统ID';
COMMENT ON COLUMN TACONFIGSYSPATH.NAME IS '系统名称';
COMMENT ON COLUMN TACONFIGSYSPATH.URL IS '系统路径前缀';
COMMENT ON COLUMN TACONFIGSYSPATH.PY IS '拼音';
COMMENT ON COLUMN TACONFIGSYSPATH.CURSYSTEM IS '是否为当前系统';

/*==============================================================*/
/* Table: TAMENU                                                */
/*==============================================================*/
CREATE TABLE TAMENU
(
   MENUID               NUMBER(10,0) NOT NULL,
   PMENUID              NUMBER(10,0) NOT NULL,
   MENUNAME             VARCHAR2(60) ,
   URL                  VARCHAR2(100) ,
   MENUIDPATH           VARCHAR2(1024) ,
   MENUNAMEPATH         VARCHAR2(1024) ,
   ICONSKIN             VARCHAR2(200) ,
   SELECTIMAGE          VARCHAR2(200) ,
   REPORTID             VARCHAR2(50) ,
   ACCESSTIMEEL         VARCHAR2(200) ,
   EFFECTIVE            CHAR(1) NOT NULL ,
   SECURITYPOLICY       CHAR(1) NOT NULL ,
   ISDISMULTIPOS        CHAR(1) NOT NULL ,
   QUICKCODE            VARCHAR2(20) ,
   SORTNO               NUMBER ,
   RESOURCETYPE         CHAR(2) NOT NULL ,
   MENULEVEL            NUMBER,
   ISLEAF               CHAR(1),
   MENUTYPE             CHAR(1),
   ISCACHE              CHAR(1), 
   SYSPATH                 VARCHAR2(20) ,
   USEYAB003				CHAR(1),
   TYPEFLAG                 NUMBER(10) ,
   constraint PK_TAMENU primary key (MENUID)
);
COMMENT ON TABLE TAMENU IS
'功能菜单';
COMMENT ON COLUMN TAMENU.MENUID IS
'菜单Id';
COMMENT ON COLUMN TAMENU.PMENUID IS
'父菜单id';
COMMENT ON COLUMN TAMENU.MENUNAME IS
'功能地址';
COMMENT ON COLUMN TAMENU.URL IS
'功能名称';
COMMENT ON COLUMN TAMENU.MENUIDPATH IS
'菜单id路径';
COMMENT ON COLUMN TAMENU.MENUNAMEPATH IS
'菜单名称路径';
COMMENT ON COLUMN TAMENU.ICONSKIN IS
'选择前图片';
COMMENT ON COLUMN TAMENU.SELECTIMAGE IS
'选择后图片';
COMMENT ON COLUMN TAMENU.REPORTID IS
'查询报表的报表id';
COMMENT ON COLUMN TAMENU.ACCESSTIMEEL IS
'访问限制时间表达式';
COMMENT ON COLUMN TAMENU.EFFECTIVE IS
'有效标志';
COMMENT ON COLUMN TAMENU.SECURITYPOLICY IS
'安全策略';
COMMENT ON COLUMN TAMENU.ISDISMULTIPOS IS
'是否显示多岗';
COMMENT ON COLUMN TAMENU.QUICKCODE IS
'快捷访问码';
COMMENT ON COLUMN TAMENU.SORTNO IS
'排序号';
COMMENT ON COLUMN TAMENU.RESOURCETYPE IS
'权限类型（功能权限\按钮权限\表单只读\表单可编辑\表格列只读\表格列可编辑）';
COMMENT ON COLUMN TAMENU.MENULEVEL IS
'菜单层级';
COMMENT ON COLUMN TAMENU.ISLEAF IS
'是否叶子节点';
COMMENT ON COLUMN TAMENU.MENUTYPE IS
'菜单类型';
COMMENT ON COLUMN TAMENU.ISCACHE IS
'是否缓存';
COMMENT ON COLUMN TAMENU.SYSPATH IS
'系统路径';
COMMENT ON COLUMN TAMENU. USEYAB003 IS
'是否启用分中心数据权限';
COMMENT ON COLUMN TAMENU.TYPEFLAG IS
'类标识';

/*==============================================================*/
/* Table: TAORG                                                 */
/*==============================================================*/
CREATE TABLE TAORG
(
   ORGID                NUMBER(10,0) NOT NULL ,
   PORGID               NUMBER(10,0),
   ORGNAME              VARCHAR2(60) ,
   COSTOMNO             VARCHAR2(10) ,
   ORGIDPATH            VARCHAR2(1024) ,
   ORGNAMEPATH          VARCHAR2(1024) ,
   COSTOMNOPATH         VARCHAR2(1024) ,
   ORGTYPE              CHAR(2) ,
   SORT                 NUMBER,
   YAB003               VARCHAR2(6) ,
   DIMENSION            CHAR(2) ,
   CREATEUSER           NUMBER(10) NOT NULL ,
   CREATETIME           DATE NOT NULL ,
   EFFECTIVE            CHAR(1) NOT NULL,
   ORGLEVEL             NUMBER(10),
   ISLEAF               CHAR(1), 
   ORGMANAGER           NUMBER(10) ,
   DESTORY             CHAR(1),
   TYPEFLAG             NUMBER(10),
   constraint PK_TAORG primary key (ORGID)
);
COMMENT ON TABLE TAORG IS
'组织视图';
COMMENT ON COLUMN TAORG.ORGID IS
'组织id';
COMMENT ON COLUMN TAORG.PORGID IS
'组织父id';
COMMENT ON COLUMN TAORG.ORGNAME IS
'组织名称';
COMMENT ON COLUMN TAORG.COSTOMNO IS
'自定义编码';
COMMENT ON COLUMN TAORG.ORGIDPATH IS
'组织id路径';
COMMENT ON COLUMN TAORG.ORGNAMEPATH IS
'组织名称路径';
COMMENT ON COLUMN TAORG.COSTOMNOPATH IS
'自定义编码路径';
COMMENT ON COLUMN TAORG.ORGTYPE IS
'组织类型（机构（集团、子公司）、部门、组）';
COMMENT ON COLUMN TAORG.SORT IS
'排序号';
COMMENT ON COLUMN TAORG.YAB003 IS
'经办机构';
COMMENT ON COLUMN TAORG.DIMENSION IS
'视图维度';
COMMENT ON COLUMN TAORG.CREATEUSER IS
'创建人';
COMMENT ON COLUMN TAORG.CREATETIME IS
'创建时间';
COMMENT ON COLUMN TAORG.EFFECTIVE IS
'有效性';
COMMENT ON COLUMN TAORG.ORGLEVEL IS
'组织层级';
COMMENT ON COLUMN TAORG.ISLEAF IS
'是否叶子节点';
COMMENT ON COLUMN TAORG.ORGMANAGER IS
'组织负责人（正职）';
COMMENT ON COLUMN TAORG.DESTORY IS
'是否销毁';
COMMENT ON COLUMN TAORG.TYPEFLAG IS
'类标识';

/*==============================================================*/
/* Table: TAORGOPLOG                                            */
/*==============================================================*/
CREATE TABLE TAORGOPLOG
(
   LOGID                NUMBER(10,0) NOT NULL ,
   BATCHNO              VARCHAR2(10) ,
   OPTYPE               CHAR(2) ,
   INFLUENCEBODYTYPE    CHAR(2) ,
   INFLUENCEBODY        VARCHAR2(10) ,
   OPBODY               CHAR(2) ,
   OPSUBJEKT            VARCHAR2(10),
   CHANGCONTENT         VARCHAR2(2048) ,
   OPTIME               DATE NOT NULL ,
   OPUSER               VARCHAR2(10) NOT NULL ,
   OPPOSITION           VARCHAR2(10) NOT NULL ,
   constraint PK_TAORGOPLOG primary key (LOGID)
);
COMMENT ON TABLE TAORGOPLOG IS
'组织及权限操作日志';
COMMENT ON COLUMN TAORGOPLOG.LOGID IS
'日志id';
COMMENT ON COLUMN TAORGOPLOG.BATCHNO IS
'操作批次号';
COMMENT ON COLUMN TAORGOPLOG.OPTYPE IS
'操作类型（新增、编辑、删除、授权、回收权限）';
COMMENT ON COLUMN TAORGOPLOG.INFLUENCEBODYTYPE IS
'影响主体类型（组织、人员、岗位、角色、权限资源）';
COMMENT ON COLUMN TAORGOPLOG.INFLUENCEBODY IS
'影响主体';
COMMENT ON COLUMN TAORGOPLOG.OPBODY IS
'操作主体类型（人员、组织、岗位、角色、权限资源）';
COMMENT ON COLUMN TAORGOPLOG.OPSUBJEKT IS
'操作主体';
COMMENT ON COLUMN TAORGOPLOG.CHANGCONTENT IS
'主体变更内容';
COMMENT ON COLUMN TAORGOPLOG.OPTIME IS
'经办时间';
COMMENT ON COLUMN TAORGOPLOG.OPUSER IS
'经办人';
COMMENT ON COLUMN TAORGOPLOG.OPPOSITION IS
'经办岗位';

/*==============================================================*/
/* Table: TAPOSITION                                            */
/*==============================================================*/
CREATE TABLE TAPOSITION
(
   POSITIONID           NUMBER(10,0) NOT NULL,
   ORGID                NUMBER(10,0) NOT NULL,
   POSITIONNAME         VARCHAR2(60) NOT NULL ,
   POSITIONTYPE         CHAR(1) NOT NULL ,
   CREATEPOSITIONID     NUMBER(10,0) NOT NULL,
   ORGIDPATH            VARCHAR2(1024),
   ORGNAMEPATH          VARCHAR2(1024),
   VALIDTIME            DATE ,
   CREATEUSER           NUMBER(10,0) NOT NULL ,
   CREATETIME           DATE NOT NULL,
   EFFECTIVE            CHAR(1) NOT NULL,
   ISADMIN              CHAR(1), 
   ISSHARE               CHAR(1),
   ISCOPY                  CHAR(1),
   TYPEFLAG                  NUMBER(10),
   constraint PK_TAPOSITION primary key (POSITIONID)
);
COMMENT ON TABLE TAPOSITION IS
'岗位';
COMMENT ON COLUMN TAPOSITION.POSITIONID IS
'岗位id';
COMMENT ON COLUMN TAPOSITION.ORGID IS
'组织id';
COMMENT ON COLUMN TAPOSITION.POSITIONNAME IS
'岗位名称';
COMMENT ON COLUMN TAPOSITION.POSITIONTYPE IS
'岗位类型（个人专属岗位/公有岗位）';
COMMENT ON COLUMN TAPOSITION.CREATEPOSITIONID IS
'创建人使用的岗位';
COMMENT ON COLUMN TAPOSITION.ORGIDPATH IS
'所在组织id路径';
COMMENT ON COLUMN TAPOSITION.ORGNAMEPATH IS
'所在组织名称路径';
COMMENT ON COLUMN TAPOSITION.VALIDTIME IS
'只针对委派生成的岗位';
COMMENT ON COLUMN TAPOSITION.CREATEUSER IS
'创建人';
COMMENT ON COLUMN TAPOSITION.CREATETIME IS
'创建时间';
COMMENT ON COLUMN TAPOSITION.EFFECTIVE IS
'有效标志';
COMMENT ON COLUMN TAPOSITION.ISADMIN IS
'是否管理员';
COMMENT ON COLUMN TAPOSITION.ISSHARE IS
'是否为共享岗位';
COMMENT ON COLUMN TAPOSITION.ISCOPY IS
'是否为复制岗位';
COMMENT ON COLUMN TAPOSITION.TYPEFLAG IS
'类标识';

/*==============================================================*/
/* Table: TAPOSITIONAUTHRITY                                    */
/*==============================================================*/
CREATE TABLE TAPOSITIONAUTHRITY
(
   POSITIONID           NUMBER(10,0) NOT NULL ,
   MENUID               NUMBER(10,0) NOT NULL ,
   USEPERMISSION        CHAR(1),
   REPERMISSION         CHAR(1) ,
   REAUTHRITY           CHAR(1),
   CREATEUSER           NUMBER(10,0) NOT NULL ,
   CREATETIME           DATE NOT NULL ,
   EFFECTTIME           DATE , 
   constraint PK_TAPOSITIONAUTHRITY primary key (POSITIONID, MENUID)
);
COMMENT ON TABLE TAPOSITIONAUTHRITY IS
'岗位权限表';
COMMENT ON COLUMN TAPOSITIONAUTHRITY.POSITIONID IS
'岗位id';
COMMENT ON COLUMN TAPOSITIONAUTHRITY.MENUID IS
'菜单Id';
COMMENT ON COLUMN TAPOSITIONAUTHRITY.USEPERMISSION IS
'使用权限';
COMMENT ON COLUMN TAPOSITIONAUTHRITY.REPERMISSION IS
'授权别人使用权限';
COMMENT ON COLUMN TAPOSITIONAUTHRITY.REAUTHRITY IS
'授权别人授权权限';
COMMENT ON COLUMN TAPOSITIONAUTHRITY.CREATEUSER IS
'创建人';
COMMENT ON COLUMN TAPOSITIONAUTHRITY.CREATETIME IS
'创建时间';
COMMENT ON COLUMN TAPOSITIONAUTHRITY.EFFECTTIME IS
'有效时间';

/*==============================================================*/
/* Table: TAUSER                                                */
/*==============================================================*/
CREATE TABLE TAUSER
(
   USERID               NUMBER(10,0) NOT NULL ,
   NAME                 VARCHAR2(60) NOT NULL ,
   SEX                  CHAR(1) ,
   LOGINID              VARCHAR2(20) NOT NULL ,
   PASSWORD             VARCHAR2(50) NOT NULL ,
   PASSWORDFAULTNUM     NUMBER ,
   PWDLASTMODIFYDATE    DATE ,
   ISLOCK               CHAR(1) ,
   SORT                 NUMBER ,
   EFFECTIVE            CHAR(1) NOT NULL ,
   TEL                  VARCHAR2(15) ,
   CREATEUSER           NUMBER(10,0) ,
   CREATETIME           DATE NOT NULL ,
   DIRECTORGID        NUMBER(10,0) NOT NULL,
   DESTORY				CHAR(1),
   TYPEFLAG        NUMBER(10,0) ,
   constraint PK_TAUSER primary key (USERID)
);
COMMENT ON TABLE TAUSER IS
'人员';
COMMENT ON COLUMN TAUSER.USERID IS
'人员id';
COMMENT ON COLUMN TAUSER.NAME IS
'姓名';
COMMENT ON COLUMN TAUSER.SEX IS
'性别';
COMMENT ON COLUMN TAUSER.LOGINID IS
'登陆账号';
COMMENT ON COLUMN TAUSER.PASSWORD IS
'密码';
COMMENT ON COLUMN TAUSER.PASSWORDFAULTNUM IS
'口令错误次数';
COMMENT ON COLUMN TAUSER.PWDLASTMODIFYDATE IS
'口令最后修改时间';
COMMENT ON COLUMN TAUSER.ISLOCK IS
'锁定标志';
COMMENT ON COLUMN TAUSER.SORT IS
'排序号';
COMMENT ON COLUMN TAUSER.EFFECTIVE IS
'有效标志';
COMMENT ON COLUMN TAUSER.TEL IS
'联系电话';
COMMENT ON COLUMN TAUSER.CREATEUSER IS
'创建人';
COMMENT ON COLUMN TAUSER.CREATETIME IS
'创建时间';
COMMENT ON COLUMN TAUSER.DIRECTORGID IS
'直属组织';
COMMENT ON COLUMN TAUSER.DESTORY IS
'是否销毁';
COMMENT ON COLUMN TAUSER.TYPEFLAG IS
'类标识';

/*==============================================================*/
/* Table: TAUSERPOSITION                                        */
/*==============================================================*/
CREATE TABLE TAUSERPOSITION
(
   USERID               NUMBER(10,0) NOT NULL ,
   POSITIONID           NUMBER(10,0) NOT NULL ,
   MAINPOSITION         CHAR(1) NOT NULL ,
   CREATEUSER           NUMBER(10,0) NOT NULL ,
   CREATETIME           DATE NOT NULL ,
   constraint PK_TAUSERPOSITION primary key (USERID, POSITIONID)
);
COMMENT ON TABLE TAUSERPOSITION IS
'人员岗位关系表';
COMMENT ON COLUMN TAUSERPOSITION.USERID IS
'人员id';
COMMENT ON COLUMN TAUSERPOSITION.POSITIONID IS
'岗位id';
COMMENT ON COLUMN TAUSERPOSITION.MAINPOSITION IS
'默认岗位';
COMMENT ON COLUMN TAUSERPOSITION.CREATEUSER IS
'创建人';
COMMENT ON COLUMN TAUSERPOSITION.CREATETIME IS
'创建时间';

/*==============================================================*/
/* Table: TAORGMG                                               */
/*==============================================================*/
CREATE TABLE TAORGMG
(
   POSITIONID           NUMBER(10,0) ,
   ORGID                NUMBER(10,0) 
);
COMMENT ON TABLE TAORGMG IS
'组织管理表';
COMMENT ON COLUMN TAORGMG.POSITIONID IS
'岗位id';
COMMENT ON COLUMN TAORGMG.ORGID IS
'组织id';

/*==============================================================*/
/* Table: TAMANAGERMG                                               */
/*==============================================================*/
CREATE TABLE TAMANAGERMG
(
   POSITIONID           NUMBER(10,0) ,
   ORGID                NUMBER(10,0) 
);
COMMENT ON TABLE TAMANAGERMG IS
'组织负责人（副职）管理表';
COMMENT ON COLUMN TAMANAGERMG.POSITIONID IS
'岗位id';
COMMENT ON COLUMN TAMANAGERMG.ORGID IS
'组织id';
/*==============================================================*/
/* Table: TASHAREPOSITION                                               */
/*==============================================================*/
CREATE TABLE TASHAREPOSITION
(
   SPOSITIONID           NUMBER(10),
   DPOSITIONID           NUMBER(10)
);
COMMENT ON TABLE TASHAREPOSITION IS
'共享岗位表';
COMMENT ON COLUMN TASHAREPOSITION.SPOSITIONID IS
'源岗位id';
COMMENT ON COLUMN TASHAREPOSITION.DPOSITIONID IS
'复制岗位id';

/*==============================================================*/
/* Table: TAACCESSLOG                                              */
/*==============================================================*/
CREATE TABLE TAACCESSLOG (
  LOGID NUMBER(15) NOT NULL,
  USERID NUMBER(10) NOT NULL,
  POSITIONID NUMBER(10) NOT NULL ,
  PERMISSIONID NUMBER(10) NOT NULL ,
  ISPERMISSION CHAR(1) NOT NULL,
  ACCESSTIME DATE NOT NULL,
  constraint PK_TAACCESSLOG primary key (LOGID)
);
COMMENT ON TABLE TAACCESSLOG IS
'功能日志表';
COMMENT ON COLUMN TAACCESSLOG.LOGID IS
'日志id';
COMMENT ON COLUMN TAACCESSLOG.USERID IS
'用户id';
COMMENT ON COLUMN TAACCESSLOG.POSITIONID IS
'岗位id';
COMMENT ON COLUMN TAACCESSLOG.PERMISSIONID IS
'功能id';
COMMENT ON COLUMN TAACCESSLOG.ISPERMISSION IS
'是否有权限';
COMMENT ON COLUMN TAACCESSLOG.ACCESSTIME IS
'访问时间';

/*==============================================================*/
/* Table: TAMENUPOSITIONYAB003                                            */
/*==============================================================*/
CREATE TABLE TAMENUPOSITIONYAB003 (
  MENUID NUMBER(10) NOT NULL,
  POSITIONID NUMBER(10) NOT NULL ,
  YAB003   VARCHAR2(6) NOT NULL,
  constraint PK_TAMENUPOSITIONYAB003 primary key (MENUID,POSITIONID,YAB003)
);
COMMENT ON TABLE TAMENUPOSITIONYAB003 IS
'功能数据权限';
COMMENT ON COLUMN TAMENUPOSITIONYAB003.MENUID IS
'菜单id';
COMMENT ON COLUMN TAMENUPOSITIONYAB003.POSITIONID IS
'岗位id';
COMMENT ON COLUMN TAMENUPOSITIONYAB003.YAB003 IS
'分中心';

/*==============================================================*/
/* Table:TAADMINYAB003SCOPE                                          */
/*==============================================================*/
CREATE TABLE TAADMINYAB003SCOPE (
  POSITIONID NUMBER(10) NOT NULL ,
  YAB003   VARCHAR2(6) NOT NULL,
  constraint PK_TAADMINYAB003SCOPE primary key (POSITIONID,YAB003)
);
COMMENT ON TABLE TAADMINYAB003SCOPE IS
'管理员分中心管理范围';
COMMENT ON COLUMN TAADMINYAB003SCOPE.POSITIONID IS
'岗位id';
COMMENT ON COLUMN TAADMINYAB003SCOPE.YAB003 IS
'分中心';

/*==============================================================*/
/* Table:TAYAB003SCOPE                                    */
/*==============================================================*/
CREATE TABLE TAYAB003SCOPE (
  YAB003   VARCHAR2(6) NOT NULL,
  YAB139    VARCHAR2(6) NOT NULL,
  constraint PK_TAYAB003SCOPE primary key (YAB003,YAB139)
);
COMMENT ON TABLE TAYAB003SCOPE IS
'分中心数据权限范围表';
COMMENT ON COLUMN TAYAB003SCOPE.YAB003 IS
'分中心';
COMMENT ON COLUMN TAYAB003SCOPE.YAB139 IS
'分中心数据权限';

/*==============================================================*/
/* Table: TACOMMONMENU                                               */
/*==============================================================*/
CREATE TABLE TACOMMONMENU (
  USERID NUMBER(10) NOT NULL,
  MENUID NUMBER(10) NOT NULL,
 constraint PK_TACOMMONMENU  PRIMARY KEY (USERID,MENUID)
) ;
COMMENT ON TABLE TACOMMONMENU
  IS '常用菜单';
COMMENT ON COLUMN TACOMMONMENU.USERID IS
'用户id';
COMMENT ON COLUMN TACOMMONMENU.MENUID IS
'菜单id';

/*==============================================================*/
/* Table: TACONSOLEMODULE                                               */
/*==============================================================*/
CREATE TABLE TACONSOLEMODULE
(
  MODULE_ID      NUMBER(10) not null,
  MODULE_NAME    VARCHAR2(100) not null,
  MODULE_URL     VARCHAR2(200) not null,
  MODULE_STA     VARCHAR2(1) default 1 not null,
  MODULE_DEFAULT VARCHAR2(1) default 1,
  MODULE_HEIGHT  VARCHAR2(10) default 200
);

COMMENT ON TABLE TACONSOLEMODULE
  IS 'ECADMIN工作台自定义组件';
COMMENT ON COLUMN TACONSOLEMODULE.MODULE_ID
  IS '模块编号';
COMMENT ON COLUMN TACONSOLEMODULE.MODULE_NAME
  IS '模块名称';
COMMENT ON COLUMN TACONSOLEMODULE.MODULE_URL
  IS '模块链接';
COMMENT ON COLUMN TACONSOLEMODULE.MODULE_STA
  IS '模块有效标识';
COMMENT ON COLUMN TACONSOLEMODULE.MODULE_DEFAULT
  IS '是否默认显示';
COMMENT ON COLUMN TACONSOLEMODULE.MODULE_HEIGHT
  is '模块默认高度';
ALTER TABLE TACONSOLEMODULE
  ADD CONSTRAINT PK_ECADMIN_CONSLE_MODULE PRIMARY KEY (MODULE_ID);
  
/*==============================================================*/
/* Table: TACONSOLEMODULELOCATION                                               */
/*==============================================================*/
CREATE TABLE TACONSOLEMODULELOCATION
(
  MARK       VARCHAR2(20) NOT NULL,
  POSITIONID NUMBER(10) NOT NULL,
  LOCATION   VARCHAR2(1000) NOT NULL
);

COMMENT ON TABLE TACONSOLEMODULELOCATION
  IS 'ECADMIN工作台自定义组件位置信息';
COMMENT ON COLUMN TACONSOLEMODULELOCATION.MARK
  IS '页面标识';
COMMENT ON COLUMN TACONSOLEMODULELOCATION.POSITIONID
  IS '岗位ID';
COMMENT ON COLUMN TACONSOLEMODULELOCATION.LOCATION
  IS '位置信息数据';
  
/*==============================================================*/
/* Table: TACONSOLEMODULEPRIVILEGE                                               */
/*==============================================================*/
CREATE TABLE TACONSOLEMODULEPRIVILEGE
(
  POSITIONID NUMBER(10) NOT NULL,
  MODULEID   NUMBER(10) NOT NULL
);
 
COMMENT ON TABLE TACONSOLEMODULEPRIVILEGE
  IS 'CRM工作台自定义组件权限信息';
COMMENT ON COLUMN TACONSOLEMODULEPRIVILEGE.POSITIONID
  IS '角色编号';
COMMENT ON COLUMN TACONSOLEMODULEPRIVILEGE.MODULEID
  IS '模块编号';
ALTER TABLE TACONSOLEMODULEPRIVILEGE
  ADD CONSTRAINT PK_CRM_CONSLE_MODULE_PRIVILEGE PRIMARY KEY (POSITIONID, MODULEID);

CREATE TABLE SERVERADDRESS(  
	ADDRESS VARCHAR2(200) NOT NULL,  
	CANUSE  VARCHAR2(1)
);
COMMENT ON TABLE SERVERADDRESS IS '集群各个SERVER的应用地址';
COMMENT ON COLUMN SERVERADDRESS.ADDRESS  IS '应用地址';
COMMENT ON COLUMN SERVERADDRESS.CANUSE  IS '是否启用';
ALTER TABLE SERVERADDRESS  ADD CONSTRAINT PK_SERVERADDRESS PRIMARY KEY (ADDRESS)  USING INDEX;

create table TALOGINHISTORYLOG
(
  logid      NUMBER(15) not null,
  userid     NUMBER(10) not null,
  logintime  DATE not null,
  logouttime DATE not null,
  clientip   VARCHAR2(200) not null,
  sessionid  VARCHAR2(200) not null,
  serverip   VARCHAR2(200),
  syspath    VARCHAR2(50)
);
ALTER TABLE TALOGINHISTORYLOG
  ADD CONSTRAINT PK_TALOGINHISTORYLOG PRIMARY KEY (LOGID);
create table TAONLINELOG
(
  logid       NUMBER(15) not null,
  userid      NUMBER(10) not null,
  logintime   DATE not null,
  curresource VARCHAR2(1000),
  clientip    VARCHAR2(200) not null,
  sessionid   VARCHAR2(200) not null,
  syspath     VARCHAR2(50),
  serverip    VARCHAR2(200)
);
ALTER TABLE TAONLINELOG
  ADD CONSTRAINT PK_TAONLINELOG PRIMARY KEY (LOGID);

DROP TABLE TALOCALCACHEVERSION CASCADE CONSTRAINTS;
/*==============================================================*/
/* Table: TALOCALCACHEVERSION                                   */
/*==============================================================*/
CREATE TABLE TALOCALCACHEVERSION
(
   VERSION		NUMBER(11) NOT NULL,
   CODETYPE		VARCHAR2(20)
);
COMMENT ON TABLE TALOCALCACHEVERSION
  IS '本地缓存码表版本号';
COMMENT ON COLUMN TALOCALCACHEVERSION.VERSION
  IS '版本号';
COMMENT ON COLUMN TALOCALCACHEVERSION.CODETYPE
  IS '改动的type';
insert into TALOCALCACHEVERSION(VERSION, CODETYPE)
values (1,'');

insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('MENUTYPE', '菜单类型', '0', '通用菜单', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('MENUTYPE', '菜单类型', '1', '系统管理菜单', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('MENUTYPE', '菜单类型', '2', '业务功能菜单', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POSITIONTYPE', '岗位类型', '1', '公有岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POSITIONTYPE', '岗位类型', '2', '个人岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POSITIONTYPE', '岗位类型', '3', '委派岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('SEX', '性别', '1', '男', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('SEX', '性别', '2', '女', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('SEX', '性别', '0', '无', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('ORGTYPE', '组织类型', '01', '机构', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('ORGTYPE', '组织类型', '02', '部门', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('ORGTYPE', '组织类型', '04', '组', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('EFFECTIVE', '有效标志', '0', '有效', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('EFFECTIVE', '有效标志', '1', '无效', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('YESORNO', '是否', '0', '是', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('YESORNO', '是否', '1', '否', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POLICY', '安全策略', '1', '要认证要显示', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POLICY', '安全策略', '2', '要认证不显示', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POLICY', '安全策略', '3', '不认证不显示', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POLICY', '安全策略', '4', '不认证要显示', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '01', '新增组织', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '02', '编辑组织', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '03', '禁用组织', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '04', '新增人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '05', '编辑人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '06', '禁用人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '07', '密码重置', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '08', '赋予岗位给人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '09', '设置主岗位给人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '10', '新增岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '11', '编辑岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '12', '禁用岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '13', '赋予岗位使用权限', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '14', '回收岗位使用权限', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '15', '启用岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '16', '启用人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '17', '启用组织', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '18', '删除组织', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '19', '赋予岗位授权别人使用权限', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '20', '回收岗位授权别人使用权限', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '21', '赋予岗位授权别人授权权限', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '22', '回收岗位授权别人授权权限', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '23', '删除管理员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '24', '新增管理员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '25', '删除岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '操作类型', '26', '删除人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPOBJTYPE', '操作对象类型', '01', '组织', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPOBJTYPE', '操作对象类型', '02', '人员', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPOBJTYPE', '操作对象类型', '03', '岗位', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPOBJTYPE', '操作对象类型', '04', '权限', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('YAB003', '分中心', '9999', '9999', '9999', '0', 0);

INSERT INTO TACONFIGSYSPATH (SERIALID, ID, NAME, URL, PY, CURSYSTEM) values('1','sysmg','系统管理','http://127.0.0.1:8080/ta3/','xtgl','0');

INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('1','0','银海软件',NULL,'1','银海软件','tree-apply',NULL,NULL,NULL,'0','1','0',NULL,'0','01','1','1','0',NULL,'sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('2','1','系统管理',NULL,'1/2','银海软件/系统管理','tree-apply',NULL,NULL,NULL,'0','1','0',NULL,'0','01','2','1','1',NULL,'sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('3','2','菜单管理','sysapp/menuMgAction.do','1/2/3','银海软件/系统管理/菜单管理','tree-setting',NULL,NULL,NULL,'0','1','0',NULL,'0','01','3','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('18','2','系统参数管理','sysapp/configMgAction.do','1/2/18','银海软件/系统管理/系统参数管理','tree-preferences-system',NULL,NULL,NULL,'0','1','0',NULL,'3','01','3','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('4','2','组织权限管理',NULL,'1/2/4','银海软件/系统管理/组织权限管理','tree-view-refresh',NULL,NULL,NULL,'0','1','1',NULL,'1','01','3','1','1',NULL,'sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('5','4','用户功能权限管理','org/position/personalPositionMgAction.do','1/2/4/5','银海软件/系统管理/组织权限管理/用户功能权限管理','tree-user',NULL,NULL,NULL,'0','1','1',NULL,'3','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('6','4','岗位及权限管理','org/position/positionMgAction.do','1/2/4/6','银海软件/系统管理/组织权限管理/岗位及权限管理','tree-users',NULL,NULL,NULL,'0','1','1',NULL,'4','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('7','4','管理员管理','org/position/adminMgAction.do','1/2/4/7','银海软件/系统管理/组织权限管理/管理员管理','tree-userm',NULL,NULL,NULL,'0','1','1',NULL,'2','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('9','4','用户管理','org/userMgAction.do','1/2/4/9','银海软件/系统管理/组织权限管理/用户管理','tree-group',NULL,NULL,NULL,'0','1','1',NULL,'1','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('10','4','组织管理','org/orgMgAction.do','1/2/4/10','银海软件/系统管理/组织权限管理/组织管理','tree-organisation',NULL,NULL,NULL,'0','1','1',NULL,'0','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('11','4','用户岗位设置','org/position/positionSettingMgAction.do','1/2/4/11','银海软件/系统管理/组织权限管理/用户岗位设置','tree-preferences-system',NULL,NULL,NULL,'0','1','1',NULL,'5','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('12','4','功能权限代理','org/position/delegatePositionAction.do','1/2/4/12','银海软件/系统管理/组织权限管理/功能权限代理','tree-mail-send-receive',NULL,NULL,NULL,'0','1','1',NULL,'6','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('13','4','相似权限授权','org/position/similarAuthorityAction.do','1/2/4/13','银海软件/系统管理/组织权限管理/相似权限授权','tree-view-refresh',NULL,NULL,NULL,'0','1','1',NULL,'7','01','4','0','1',NULL,'sysmg',0);
--INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('14','4','分中心数据权限范围管理','org/position/yab003ScopeMgAction.do','1/2/4/14','银海软件/系统管理/组织权限管理/分中心数据权限范围管理','tree-text-editor',NULL,NULL,NULL,'0','1','1',NULL,'8','01','4','0','1',NULL,'sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('15','2','工作台管理','','1/2/15','银海软件/系统管理/工作台管理','tree-destop','','','','0','1','1','','2','01','3','1','1','','sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('16','15','工作台模块管理','sysapp/moduleMainAction.do','1/2/15/16','银海软件/系统管理/工作台管理/工作台模块管理','tree-menu','','','','0','1','1','','0','01','4','0','1','','sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('17','15','模块授权管理','sysapp/moduleMainAction!toGrant.do','1/2/15/17','银海软件/系统管理/工作台管理/模块授权管理','tree-star','','','','0','1','1','','1','01','4','0','1','','sysmg',0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('19','2', '代码表查看', 'sysapp/appCodeMainAction.do', '1/2/19', '银海软件/系统管理/代码表查看', 'tree-system-search', NULL, NULL, NULL, '0', '1', '1', NULL, 3, '01', 3, '0', '1', NULL, 'sysmg', 0);
INSERT INTO TAMENU (MENUID,PMENUID,MENUNAME,URL,MENUIDPATH,MENUNAMEPATH,ICONSKIN,SELECTIMAGE,REPORTID,ACCESSTIMEEL,EFFECTIVE,SECURITYPOLICY,ISDISMULTIPOS,QUICKCODE,SORTNO,RESOURCETYPE,MENULEVEL,ISLEAF,MENUTYPE,ISCACHE,SYSPATH,TYPEFLAG) values('20','2', '集群server地址配置', 'sysapp/serverAddressAction.do', '1/2/20', '银海软件/系统管理/集群server地址配置', 'btn-setting', NULL, NULL, NULL, '0', '1', '1', NULL, 4, '01', 3, '0', '1', NULL, 'sysmg', 0);
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG) values ('21', '4', '批量导入组织人员', 'org/upload/uploadOrgUserAction.do', '1/2/4/21', '银海软件/系统管理/组织权限管理/批量导入组织人员', 'tree-edit-redo', '', '', '', '0', '1', '1', '', 9, '01', 4, '0', '1', '', 'sysmg', '', 0);
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG) values ('22', '2', '系统Exception日志', 'sysapp/serverExeceptionLogAction.do', '1/2/22', '银海软件/系统管理/系统Exception日志', 'tree-document-new', NULL, NULL, NULL, '0', '1', '1', NULL, 6, '01', 3, '0', '1', NULL, 'sysmg', NULL, 0);

INSERT INTO TAORG (ORGID,PORGID,ORGNAME,COSTOMNO,ORGIDPATH,ORGNAMEPATH,COSTOMNOPATH,ORGTYPE,SORT,YAB003,DIMENSION,CREATEUSER,CREATETIME,EFFECTIVE,ORGLEVEL,ISLEAF,TYPEFLAG) VALUES (1,1,'银海软件','1','1','银海软件','0','01',0,'9999',NULL,0,sysdate,'0',0,'0',0);

INSERT INTO TAUSER (USERID,NAME,SEX,LOGINID,PASSWORD,PASSWORDFAULTNUM,PWDLASTMODIFYDATE,ISLOCK,SORT,EFFECTIVE,TEL,CREATEUSER,CREATETIME,DIRECTORGID,TYPEFLAG) VALUES (1,'超级管理员','1','developer','oi89/VUCsAnxdEQN90B/qA==',0,sysdate,'0',0,'0','0',1,sysdate,1,0);

INSERT INTO TAPOSITION (POSITIONID,ORGID,POSITIONNAME,POSITIONTYPE,CREATEPOSITIONID,ORGIDPATH,ORGNAMEPATH,VALIDTIME,CREATEUSER,CREATETIME,EFFECTIVE,ISADMIN,TYPEFLAG) VALUES (1,1,'超级管理员','1',1,'1','银海软件',NULL,1,sysdate,'0','1',0);

INSERT INTO TAUSERPOSITION (USERID,POSITIONID,MAINPOSITION,CREATEUSER,CREATETIME) VALUES (1,1,'1',1,sysdate);

ALTER TABLE TAORGMG ADD CONSTRAINT FK_REFERENCE_8 FOREIGN KEY (ORGID)
      REFERENCES TAORG (ORGID);

ALTER TABLE TAORGMG ADD CONSTRAINT FK_REFERENCE_9 FOREIGN KEY (POSITIONID)
      REFERENCES TAPOSITION (POSITIONID) ;

ALTER TABLE TAORG ADD CONSTRAINT FK_REFERENCE_6 FOREIGN KEY (PORGID)
      REFERENCES TAORG (ORGID) ;

ALTER TABLE TAPOSITION ADD CONSTRAINT FK_RELATIONSHIP_5 FOREIGN KEY (ORGID)
      REFERENCES TAORG (ORGID) ;

ALTER TABLE TAPOSITIONAUTHRITY ADD CONSTRAINT FK_REFERENCE_7 FOREIGN KEY (MENUID)
      REFERENCES TAMENU (MENUID) ;

ALTER TABLE TAPOSITIONAUTHRITY ADD CONSTRAINT FK_RELATIONSHIP_11 FOREIGN KEY (POSITIONID)
      REFERENCES TAPOSITION (POSITIONID) ;

ALTER TABLE TAUSERPOSITION ADD CONSTRAINT FK_RELATIONSHIP_10 FOREIGN KEY (POSITIONID)
      REFERENCES TAPOSITION (POSITIONID) ;

ALTER TABLE TAUSERPOSITION ADD CONSTRAINT FK_RELATIONSHIP_9 FOREIGN KEY (USERID)
      REFERENCES TAUSER (USERID);

CREATE OR REPLACE view AA10A1(
      AAA100 ,
      AAA101 ,
      AAA102 ,
      AAA103 ,
      YAB003 ,
      AAE120 ,
      ver) AS
select
   AAA100,
   AAA101,
   AAA102,
   AAA103,
   YAB003,
   AAE120,
   VER
from
   AA10;
commit;

